# Generated by Django 4.2.9 on 2024-09-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_prodact_images_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
