# Generated by Django 4.2.9 on 2024-09-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_Media_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='images')),
                ('link', models.TextField(max_length=50)),
            ],
        ),
    ]
