# Generated by Django 4.2.9 on 2024-09-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_social_media_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social_media_images',
            name='description',
        ),
    ]
