# Generated by Django 4.2.9 on 2024-09-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_remove_social_media_images_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Konum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konum', models.TextField(verbose_name=50)),
                ('mail', models.TextField(max_length=15)),
                ('telefon', models.TextField(max_length=11)),
            ],
        ),
    ]
