# Generated by Django 4.2.9 on 2024-09-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_konum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konum',
            name='konum',
            field=models.TextField(max_length=50),
        ),
        migrations.CreateModel(
            name='home_prodact_kategorileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=20)),
                ('aciklama', models.TextField(max_length=50)),
                ('isActive', models.BooleanField()),
                ('ürünler', models.ManyToManyField(to='Home.prodact')),
            ],
        ),
    ]
