# Generated by Django 4.2.9 on 2024-09-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_konum_konum_home_prodact_kategorileri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_prodact_kategorileri',
            old_name='ürünler',
            new_name='urunler',
        ),
    ]
