# Generated by Django 4.2.9 on 2024-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_rename_ürünler_home_prodact_kategorileri_urunler'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=20)),
                ('aciklama', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='intro_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='sirketler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('title', models.TextField(max_length=20)),
                ('description', models.TextField(max_length=12)),
            ],
        ),
    ]
